name: C++ CI

on: [push, pull_request]  # Запуск при пуше или PR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Клонирует репозиторий

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ cmake

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run
        run: ./build/my_program.exe  # Замените на имя вашего исполняемого файла