name: Generate Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Doxygen
      run: |
        choco install doxygen.install --version=1.9.1 -y --no-progress
        if (!(Test-Path "C:\Program Files\doxygen\bin\doxygen.exe")) {
          Write-Error "Doxygen installation failed!"
          exit 1
        }

    - name: Generate Documentation
      run: |
        $doxygenPath = "C:\Program Files\doxygen\bin\doxygen.exe"
        & "$doxygenPath" Doxyfile

    - name: Verify Documentation
      run: |
        if (!(Test-Path "docs\html")) {
          Write-Error "Documentation was not generated!"
          exit 1
        }
        dir docs\html

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/html